name: Reusable ESLint Workflow
on:
  pull_request:
    paths:
      - '**/*.js'
  push:
    branches:
      - main

jobs:
  format:
    uses: squarebtech/reusable-workflows/.github/workflows/test-prettier.yaml@main
    with:
      node-version: '20'
      working-directory: './'
  lint:
    uses: squarebtech/reusable-workflows/.github/workflows/test-eslint.yaml@main
    with:
      node-version: '20'
      working-directory: './'
